#配置端口和path路径
server:
  #port: 8831
  session:
    tracking-modes: cookie
  servlet-path: /
  max-http-header-size: 1048576
  tomcat:
    max-connections: 3000
    max-http-post-size: 1048576
    max-threads: 1000
  
  
#配置当前profiles
spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: git@gitee.com:xinzhuxiansheng/springcloud-config.git

#配置日志
logging:
  config: classpath:log4j2.xml


